### ISSUE TITLE
Do not write to .Last.value

### ISSUE THREAD

**Issue by driesbenoit** [dodona-edu/judge-r#11]
The R doc warns against writing to .Last.value as it masks the internal/global .Last.value object. See:
> ?.Last.value

I'd suggest to use a different object (user-defined) to store the last value of the student script, i.e.
> assign("lastValue",
>            eval(parse(text = read_lines(student_code)), envir = test_env$clean_env),
>            envir = test_env$clean_env)

Also, in the readme.md, the following sentence:

"This value is now catched and assigned to the variable .Last.value in the test environment and can be accessed using env$.Last.value."

is not correct, it should be the "**student** environment".

I did not make these changes in a PR, because this would impact the exercises already written. If you agree, I can make the changes and issue a PR.

**Comment by ninewise** [comment]
Both seem right to me. Maybe even use `studentLastValue` to make obvious in the code this is the student environment.

Creating a PR is always safe, only merging it would influence the master branch and change the judge on Dodona.
