### ISSUE TITLE
'Cannot open connection to' error

### ISSUE THREAD

**Issue by DieterPi** [dodona-edu/judge-r#75]
I've made an exercise where data is downloaded from KMI and analysed in R. However for the [feedback](https://github.com/RobbeW/Data_Statistiek_R/blob/main/Deel%201%20Beschrijvend/01%20Inleiding/Ukkel/evaluation/Feedback.R) the following error appears

`Error while evaluating context: cannot open the connection to 'https://www.meteo.be/resources/climatology/uccle_month/Ukkel_waarnemingen.txt'`

How can I resolve this?

**Comment by chvp** [comment]
Are you sure you enabled the network for your exercise? The error seems to point in the direction of no internet being available.

**Comment by bmesuere** [comment]
By default, network access is disabled for the docker containers where the tests are run. You should set `network_enabled` to true in the config. See https://docs.dodona.be/en/references/exercise-config/#config-file-structure-for-exercises for more information.

**Comment by DieterPi** [comment]
> By default, network access is disabled for the docker containers where the tests are run. You should set `network_enabled` to true in the config. See https://docs.dodona.be/en/references/exercise-config/#config-file-structure-for-exercises for more information.

This fixed the issue, thanks for the quick response!
