### ISSUE TITLE
Can `exists` be used in a testplan?

### ISSUE THREAD

**Issue by DieterPi** [dodona-edu/judge-r#76]
Is there a way to implement something like this in a R-testplan?

```R
testcase("You no longer have the som variable:", {
    testEqual("", function(env) {
      !exists("som")
    }, TRUE)
  })
```

**Comment by chvp** [comment]
To be clear, you would like a test function to see if a variable exists in the student's env? That's currently not supported, but wouldn't be too much effort to add I think.

**Comment by DieterPi** [comment]
> To be clear, you would like a test function to see if a variable exists (or doesn't exist) in the student's env? That's currently not supported, but wouldn't be too much effort to add I think.

Yeah, that would be the request :)
